# Generated by Django 5.2.8 on 2025-11-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_gerenciados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIRETOR', 'Diretor'), ('GESTOR', 'Gestor'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('departamentos', models.ManyToManyField(blank=True, related_name='perfis', to='core.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('participantes', models.ManyToManyField(related_name='viagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_despesa', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('HOSPEDAGEM', 'Hospedagem'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50)),
                ('comprovante', models.FileField(upload_to='comprovantes/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacao_rejeicao', models.TextField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_adiantamento', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante_deposito', models.FileField(blank=True, null=True, upload_to='comprovantes_adiantamentos/%Y/%m/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='core.viagem')),
            ],
        ),
    ]
